{% set version = "3.7.0" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: f06876c926b8cf88b2f0f68d6cda2b0ff86002385877c9867970e1d017ef82a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jdatetime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slashmili/python-jalali
  summary: Jalali datetime binding for python
  doc_url: https://pythonhosted.org/jdatetime/
  license: PSF-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
