{% set version = "3.8.2" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: c685687e3f39e1b9a3ba9c00ed9d8e88603bc8994413e84623e6c5d43214e6f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jdatetime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slashmili/python-jalali
  summary: Jalali datetime binding for python
  doc_url: https://pythonhosted.org/jdatetime/
  license: PSF-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
