{% set version = "3.6.2" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: a589e35f0dab89283c1a3de9d70ed6cf657932aaed8e8ce1b0e5801aaab1da67

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jdatetime

about:
  home: https://github.com/slashmili/python-jalali
  license: PSF
  license_file: LICENSE
  summary: 'Jalali datetime binding for python'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
