{% set version = "3.2.0" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: 42d0d08c0d36dcf1c4e1ddb1d10338d0dffb94105a02d74b6ea655ee8dd93cc2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jdatetime

about:
  home: https://github.com/slashmili/python-jalali
  license: PSF
  summary: 'Jalali datetime binding for python'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
