{% set name = "jdatetime" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jdatetime-{{ version }}.tar.gz
  sha256: c81d5898717b82b609a3ce2a73f8b8d3230b0c757e5c0de9d6b1acfdc224f551

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jalali-core >=1.0

test:
  imports:
    - jdatetime
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/slashmili/python-jalali
  summary: Jalali datetime binding for python
  doc_url: https://pythonhosted.org/jdatetime/
  license: PSF-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
