{% set version = "4.1.1" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: 1dd0ee210160c7bd30002803c443e6260ac602ea65b065652a1d567d3bfdca7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - jdatetime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slashmili/python-jalali
  summary: Jalali datetime binding for python
  doc_url: https://pythonhosted.org/jdatetime/
  license: PSF-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
