travis:
  secure:
    BINSTAR_TOKEN: tMOgFe7qzBFWkVNhA3lGxz7urdFqegGEbcLuW6OltXd2BHxTVvYTM/M7UbrEldIqAu7BvIHMTjYRL4jSG6R6TPC7ylJ+sJwzJO0PQUFX2L6txAp2wApku1jLo3cwVhWrOJvFcNpf02g8B8sqom7V79hvMuJGit9j8yWLHhHuSRm2e/d8B6HSnmVgdUHiR/lJOzHcWP0wsjMAefWw/4iS+nu/afwMFsmsoJHa54n4d9D12/4tZpolSkqaPe3PxuxW/TgneX7wIFgnxHY8Bn9pfvGnJxTdWf+TcsTw/tZnW0KZGkrEArhBmKub1a+eSUikKHgPt+eVWQVj9lZtN/A3p4p7kEGQhigePgGRQzeXwYvlbhuhdj2jXrN5Sls0ICwZl011vMRIYX73SbE0ySZualLptB/fK4U8dJXLOBnIvdhyaTvVKDCIAeSYiMPAeyRI7/SPsYAZKGMS38Bbg3I3lqBkjLIgzFAdf7+c31Qg4Y25JDXTV91nq+Lou3YCN5CRrQdUDpUWG4JIVQ2bSjJWWXucQ/qxTaW+NekfQnla4tZ/F74mzOF6w2YCPVNPJ4BibKCv0L3absjbNm8+7LRtMyUA2JLanOxrlzpmRU05s8ReKcWdsh7IwK/e0talb4/PV9h3WadK+QrLxSd25m5FVF3bzZM1PSbqSq9ni5PV48s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
